/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/deepakkinni/volumegroup-controller/client/v1/apis/volumegroup/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVolumeGroups implements VolumeGroupInterface
type FakeVolumeGroups struct {
	Fake *FakeVolumegroupV1alpha1
	ns   string
}

var volumegroupsResource = schema.GroupVersionResource{Group: "volumegroup.storage.k8s.io", Version: "v1alpha1", Resource: "volumegroups"}

var volumegroupsKind = schema.GroupVersionKind{Group: "volumegroup.storage.k8s.io", Version: "v1alpha1", Kind: "VolumeGroup"}

// Get takes name of the volumeGroup, and returns the corresponding volumeGroup object, and an error if there is any.
func (c *FakeVolumeGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VolumeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(volumegroupsResource, c.ns, name), &v1alpha1.VolumeGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeGroup), err
}

// List takes label and field selectors, and returns the list of VolumeGroups that match those selectors.
func (c *FakeVolumeGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VolumeGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(volumegroupsResource, volumegroupsKind, c.ns, opts), &v1alpha1.VolumeGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VolumeGroupList{ListMeta: obj.(*v1alpha1.VolumeGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.VolumeGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested volumeGroups.
func (c *FakeVolumeGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(volumegroupsResource, c.ns, opts))

}

// Create takes the representation of a volumeGroup and creates it.  Returns the server's representation of the volumeGroup, and an error, if there is any.
func (c *FakeVolumeGroups) Create(ctx context.Context, volumeGroup *v1alpha1.VolumeGroup, opts v1.CreateOptions) (result *v1alpha1.VolumeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(volumegroupsResource, c.ns, volumeGroup), &v1alpha1.VolumeGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeGroup), err
}

// Update takes the representation of a volumeGroup and updates it. Returns the server's representation of the volumeGroup, and an error, if there is any.
func (c *FakeVolumeGroups) Update(ctx context.Context, volumeGroup *v1alpha1.VolumeGroup, opts v1.UpdateOptions) (result *v1alpha1.VolumeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(volumegroupsResource, c.ns, volumeGroup), &v1alpha1.VolumeGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVolumeGroups) UpdateStatus(ctx context.Context, volumeGroup *v1alpha1.VolumeGroup, opts v1.UpdateOptions) (*v1alpha1.VolumeGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(volumegroupsResource, "status", c.ns, volumeGroup), &v1alpha1.VolumeGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeGroup), err
}

// Delete takes name of the volumeGroup and deletes it. Returns an error if one occurs.
func (c *FakeVolumeGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(volumegroupsResource, c.ns, name, opts), &v1alpha1.VolumeGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVolumeGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(volumegroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VolumeGroupList{})
	return err
}

// Patch applies the patch and returns the patched volumeGroup.
func (c *FakeVolumeGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VolumeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(volumegroupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VolumeGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeGroup), err
}
