/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/deepakkinni/volumegroup-controller/client/v1/apis/volumegroup/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVolumeGroupContents implements VolumeGroupContentInterface
type FakeVolumeGroupContents struct {
	Fake *FakeVolumegroupV1alpha1
}

var volumegroupcontentsResource = schema.GroupVersionResource{Group: "volumegroup.storage.k8s.io", Version: "v1alpha1", Resource: "volumegroupcontents"}

var volumegroupcontentsKind = schema.GroupVersionKind{Group: "volumegroup.storage.k8s.io", Version: "v1alpha1", Kind: "VolumeGroupContent"}

// Get takes name of the volumeGroupContent, and returns the corresponding volumeGroupContent object, and an error if there is any.
func (c *FakeVolumeGroupContents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VolumeGroupContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(volumegroupcontentsResource, name), &v1alpha1.VolumeGroupContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeGroupContent), err
}

// List takes label and field selectors, and returns the list of VolumeGroupContents that match those selectors.
func (c *FakeVolumeGroupContents) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VolumeGroupContentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(volumegroupcontentsResource, volumegroupcontentsKind, opts), &v1alpha1.VolumeGroupContentList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VolumeGroupContentList{ListMeta: obj.(*v1alpha1.VolumeGroupContentList).ListMeta}
	for _, item := range obj.(*v1alpha1.VolumeGroupContentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested volumeGroupContents.
func (c *FakeVolumeGroupContents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(volumegroupcontentsResource, opts))
}

// Create takes the representation of a volumeGroupContent and creates it.  Returns the server's representation of the volumeGroupContent, and an error, if there is any.
func (c *FakeVolumeGroupContents) Create(ctx context.Context, volumeGroupContent *v1alpha1.VolumeGroupContent, opts v1.CreateOptions) (result *v1alpha1.VolumeGroupContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(volumegroupcontentsResource, volumeGroupContent), &v1alpha1.VolumeGroupContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeGroupContent), err
}

// Update takes the representation of a volumeGroupContent and updates it. Returns the server's representation of the volumeGroupContent, and an error, if there is any.
func (c *FakeVolumeGroupContents) Update(ctx context.Context, volumeGroupContent *v1alpha1.VolumeGroupContent, opts v1.UpdateOptions) (result *v1alpha1.VolumeGroupContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(volumegroupcontentsResource, volumeGroupContent), &v1alpha1.VolumeGroupContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeGroupContent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVolumeGroupContents) UpdateStatus(ctx context.Context, volumeGroupContent *v1alpha1.VolumeGroupContent, opts v1.UpdateOptions) (*v1alpha1.VolumeGroupContent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(volumegroupcontentsResource, "status", volumeGroupContent), &v1alpha1.VolumeGroupContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeGroupContent), err
}

// Delete takes name of the volumeGroupContent and deletes it. Returns an error if one occurs.
func (c *FakeVolumeGroupContents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(volumegroupcontentsResource, name, opts), &v1alpha1.VolumeGroupContent{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVolumeGroupContents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(volumegroupcontentsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VolumeGroupContentList{})
	return err
}

// Patch applies the patch and returns the patched volumeGroupContent.
func (c *FakeVolumeGroupContents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VolumeGroupContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(volumegroupcontentsResource, name, pt, data, subresources...), &v1alpha1.VolumeGroupContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeGroupContent), err
}
