/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/deepakkinni/volumegroup-controller/client/v1/apis/volumegroup/v1alpha1"
	scheme "github.com/deepakkinni/volumegroup-controller/client/v1/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VolumeGroupContentsGetter has a method to return a VolumeGroupContentInterface.
// A group's client should implement this interface.
type VolumeGroupContentsGetter interface {
	VolumeGroupContents() VolumeGroupContentInterface
}

// VolumeGroupContentInterface has methods to work with VolumeGroupContent resources.
type VolumeGroupContentInterface interface {
	Create(ctx context.Context, volumeGroupContent *v1alpha1.VolumeGroupContent, opts v1.CreateOptions) (*v1alpha1.VolumeGroupContent, error)
	Update(ctx context.Context, volumeGroupContent *v1alpha1.VolumeGroupContent, opts v1.UpdateOptions) (*v1alpha1.VolumeGroupContent, error)
	UpdateStatus(ctx context.Context, volumeGroupContent *v1alpha1.VolumeGroupContent, opts v1.UpdateOptions) (*v1alpha1.VolumeGroupContent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VolumeGroupContent, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VolumeGroupContentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VolumeGroupContent, err error)
	VolumeGroupContentExpansion
}

// volumeGroupContents implements VolumeGroupContentInterface
type volumeGroupContents struct {
	client rest.Interface
}

// newVolumeGroupContents returns a VolumeGroupContents
func newVolumeGroupContents(c *VolumegroupV1alpha1Client) *volumeGroupContents {
	return &volumeGroupContents{
		client: c.RESTClient(),
	}
}

// Get takes name of the volumeGroupContent, and returns the corresponding volumeGroupContent object, and an error if there is any.
func (c *volumeGroupContents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VolumeGroupContent, err error) {
	result = &v1alpha1.VolumeGroupContent{}
	err = c.client.Get().
		Resource("volumegroupcontents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VolumeGroupContents that match those selectors.
func (c *volumeGroupContents) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VolumeGroupContentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VolumeGroupContentList{}
	err = c.client.Get().
		Resource("volumegroupcontents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested volumeGroupContents.
func (c *volumeGroupContents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("volumegroupcontents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a volumeGroupContent and creates it.  Returns the server's representation of the volumeGroupContent, and an error, if there is any.
func (c *volumeGroupContents) Create(ctx context.Context, volumeGroupContent *v1alpha1.VolumeGroupContent, opts v1.CreateOptions) (result *v1alpha1.VolumeGroupContent, err error) {
	result = &v1alpha1.VolumeGroupContent{}
	err = c.client.Post().
		Resource("volumegroupcontents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeGroupContent).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a volumeGroupContent and updates it. Returns the server's representation of the volumeGroupContent, and an error, if there is any.
func (c *volumeGroupContents) Update(ctx context.Context, volumeGroupContent *v1alpha1.VolumeGroupContent, opts v1.UpdateOptions) (result *v1alpha1.VolumeGroupContent, err error) {
	result = &v1alpha1.VolumeGroupContent{}
	err = c.client.Put().
		Resource("volumegroupcontents").
		Name(volumeGroupContent.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeGroupContent).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *volumeGroupContents) UpdateStatus(ctx context.Context, volumeGroupContent *v1alpha1.VolumeGroupContent, opts v1.UpdateOptions) (result *v1alpha1.VolumeGroupContent, err error) {
	result = &v1alpha1.VolumeGroupContent{}
	err = c.client.Put().
		Resource("volumegroupcontents").
		Name(volumeGroupContent.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeGroupContent).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the volumeGroupContent and deletes it. Returns an error if one occurs.
func (c *volumeGroupContents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("volumegroupcontents").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *volumeGroupContents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("volumegroupcontents").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched volumeGroupContent.
func (c *volumeGroupContents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VolumeGroupContent, err error) {
	result = &v1alpha1.VolumeGroupContent{}
	err = c.client.Patch(pt).
		Resource("volumegroupcontents").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
