/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/deepakkinni/volumegroup-controller/client/v1/apis/volumegroup/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VolumeGroupClassLister helps list VolumeGroupClasses.
// All objects returned here must be treated as read-only.
type VolumeGroupClassLister interface {
	// List lists all VolumeGroupClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.VolumeGroupClass, err error)
	// Get retrieves the VolumeGroupClass from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.VolumeGroupClass, error)
	VolumeGroupClassListerExpansion
}

// volumeGroupClassLister implements the VolumeGroupClassLister interface.
type volumeGroupClassLister struct {
	indexer cache.Indexer
}

// NewVolumeGroupClassLister returns a new VolumeGroupClassLister.
func NewVolumeGroupClassLister(indexer cache.Indexer) VolumeGroupClassLister {
	return &volumeGroupClassLister{indexer: indexer}
}

// List lists all VolumeGroupClasses in the indexer.
func (s *volumeGroupClassLister) List(selector labels.Selector) (ret []*v1alpha1.VolumeGroupClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.VolumeGroupClass))
	})
	return ret, err
}

// Get retrieves the VolumeGroupClass from the index for a given name.
func (s *volumeGroupClassLister) Get(name string) (*v1alpha1.VolumeGroupClass, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("volumegroupclass"), name)
	}
	return obj.(*v1alpha1.VolumeGroupClass), nil
}
