/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	volumegroupv1alpha1 "github.com/deepakkinni/volumegroup-controller/client/v1/apis/volumegroup/v1alpha1"
	versioned "github.com/deepakkinni/volumegroup-controller/client/v1/clientset/versioned"
	internalinterfaces "github.com/deepakkinni/volumegroup-controller/client/v1/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/deepakkinni/volumegroup-controller/client/v1/listers/volumegroup/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VolumeGroupInformer provides access to a shared informer and lister for
// VolumeGroups.
type VolumeGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VolumeGroupLister
}

type volumeGroupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVolumeGroupInformer constructs a new informer for VolumeGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVolumeGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVolumeGroupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVolumeGroupInformer constructs a new informer for VolumeGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVolumeGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VolumegroupV1alpha1().VolumeGroups(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VolumegroupV1alpha1().VolumeGroups(namespace).Watch(context.TODO(), options)
			},
		},
		&volumegroupv1alpha1.VolumeGroup{},
		resyncPeriod,
		indexers,
	)
}

func (f *volumeGroupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVolumeGroupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *volumeGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&volumegroupv1alpha1.VolumeGroup{}, f.defaultInformer)
}

func (f *volumeGroupInformer) Lister() v1alpha1.VolumeGroupLister {
	return v1alpha1.NewVolumeGroupLister(f.Informer().GetIndexer())
}
