/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	volumegroupv1alpha1 "github.com/deepakkinni/volumegroup-controller/client/v1/apis/volumegroup/v1alpha1"
	versioned "github.com/deepakkinni/volumegroup-controller/client/v1/clientset/versioned"
	internalinterfaces "github.com/deepakkinni/volumegroup-controller/client/v1/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/deepakkinni/volumegroup-controller/client/v1/listers/volumegroup/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VolumeGroupContentInformer provides access to a shared informer and lister for
// VolumeGroupContents.
type VolumeGroupContentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VolumeGroupContentLister
}

type volumeGroupContentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVolumeGroupContentInformer constructs a new informer for VolumeGroupContent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVolumeGroupContentInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVolumeGroupContentInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVolumeGroupContentInformer constructs a new informer for VolumeGroupContent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVolumeGroupContentInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VolumegroupV1alpha1().VolumeGroupContents().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VolumegroupV1alpha1().VolumeGroupContents().Watch(context.TODO(), options)
			},
		},
		&volumegroupv1alpha1.VolumeGroupContent{},
		resyncPeriod,
		indexers,
	)
}

func (f *volumeGroupContentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVolumeGroupContentInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *volumeGroupContentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&volumegroupv1alpha1.VolumeGroupContent{}, f.defaultInformer)
}

func (f *volumeGroupContentInformer) Lister() v1alpha1.VolumeGroupContentLister {
	return v1alpha1.NewVolumeGroupContentLister(f.Informer().GetIndexer())
}
